import uuid
from datetime import datetime
from sqlalchemy import Column, String, Integer, Text, DateTime, Computed, UniqueConstraint
from sqlalchemy.dialects.postgresql import UUID
from app.core.database import Base


class ShelfLifeReference(Base):
    __tablename__ = "ingredient_shelf_life"

    shelf_life_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    item_name = Column(String(160), nullable=False)
    # Normalised lookup key — generated by the database, never written by the app
    item_name_key = Column(Text, Computed("lower(btrim(item_name))", persisted=True))
    category = Column(String(120))
    storage_location = Column(String, nullable=False)  # 'Pantry', 'Refrigerator', 'Freezer'
    item_state = Column(String(80), nullable=False, default="fresh")
    item_state_key = Column(Text, Computed("lower(btrim(item_state))", persisted=True))
    shelf_life_min_days = Column(Integer, nullable=False)
    shelf_life_max_days = Column(Integer, nullable=False)
    source_name = Column(String(180), nullable=False)
    source_url = Column(Text)
    source_notes = Column(Text)
    created_at = Column(DateTime, default=datetime.utcnow)

    __table_args__ = (
        UniqueConstraint(
            "item_name_key", "storage_location", "item_state_key",
            name="ingredient_shelf_life_lookup_unique",
        ),
    )
